export enum FixtureStatus {
  SCHEDULED = 'SCHEDULED',
  LIVE = 'LIVE',
  PAUSED = 'PAUSED',
  FINISHED = 'FINISHED',
  POSTPONED = 'POSTPONED',
  SUSPENDED = 'SUSPENDED',
  CANCELED = 'CANCELED',
  FIRST_HALF = 'FIRST_HALF',
  SECOND_HALF = 'SECOND_HALF',
  FIRST_HALF_EXTRA_TIME = 'FIRST_HALF_EXTRA_TIME',
  SECOND_HALF_EXTRA_TIME = 'SECOND_HALF_EXTRA_TIME',
  PENALTIES = 'PENALTIES'
}
